// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2025, Unikraft GmbH and The Unikraft CLI Authors.
// Licensed under the BSD-3-Clause License (the "License").
// You may not use this file except in compliance with the License.

package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"time"

	"charm.land/lipgloss/v2"
	"charm.land/lipgloss/v2/compat"
	"github.com/alecthomas/kong"
	"github.com/charmbracelet/colorprofile"
	"github.com/charmbracelet/x/ansi"
	"github.com/cpuguy83/go-md2man/v2/md2man"
	"unikraft.com/cli/internal/resource"
	"unikraft.com/cli/internal/resource/cmd"
	"unikraft.com/x/kingkong"
	"unikraft.com/x/log"
)

// ManCmd generates man pages for the CLI.
type ManCmd struct {
	Outdir string `arg:"" required:"" help:"Output directory for generated man pages."`

	Markdown bool `help:"Generate markdown files instead of man pages."`
	Compress bool `help:"Generate compressed man pages (with .gz extension)."`

	Section string `default:"1" help:"Man page section number."`
	Source  string `default:"Unikraft Documentation" help:"Source field for man pages."`
	Manual  string `default:"Unikraft Manual" help:"Manual field for man pages."`
}

func (c *ManCmd) Run(ctx context.Context) error {
	compat.Profile = colorprofile.NoTTY
	lipgloss.Writer.Profile = colorprofile.NoTTY
	_ = os.Setenv("NO_COLOR", "1")

	if err := os.MkdirAll(c.Outdir, 0o775); err != nil {
		return fmt.Errorf("could not create parent directories: %w", err)
	}

	parser, err := CreateParser()
	if err != nil {
		return fmt.Errorf("could not create parser: %w", err)
	}

	header := &ManHeader{
		Title:   "Unikraft CLI",
		Section: c.Section,
		Source:  c.Source,
		Manual:  c.Manual,
	}

	for child := range IterChildren(parser.Model.Node) {
		if err := generateManPage(ctx, child, header, c.Outdir, c.Markdown, c.Compress); err != nil {
			return err
		}
	}
	log.G(ctx).Debug().Str("dir", c.Outdir).Msg("Generated man pages")

	return nil
}

// ManHeader contains metadata for man page generation.
type ManHeader struct {
	Title   string
	Section string
	Date    *time.Time
	Source  string
	Manual  string
}

func generateManPage(ctx context.Context, node *kong.Node, header *ManHeader, dir string, markdown bool, compressed bool) error {
	section := header.Section
	if section == "" {
		section = "1"
	}

	basename := strings.ReplaceAll(NodePath(node), " ", "-")

	filename := filepath.Join(dir, basename+"."+section)
	if markdown {
		filename += ".md"
	}
	if compressed {
		filename += ".gz"
	}
	log.G(ctx).Debug().Str("file", filename).Msg("write")

	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer func() {
		if f != nil {
			f.Close()
		}
	}()
	var w io.Writer = f

	var gzf *gzip.Writer
	if compressed {
		gzf, err = gzip.NewWriterLevel(f, gzip.BestCompression)
		if err != nil {
			return err
		}
		defer func() {
			if gzf != nil {
				gzf.Close()
			}
		}()
		w = gzf
	}

	if err := generateMan(node, header, w, !markdown); err != nil {
		return err
	}

	if gzf != nil {
		err = gzf.Close()
		gzf = nil
		if err != nil {
			return err
		}
	}

	err = f.Close()
	f = nil
	if err != nil {
		return err
	}

	return nil
}

func generateMan(node *kong.Node, header *ManHeader, w io.Writer, translate bool) error {
	if err := fillManHeader(header, NodePath(node)); err != nil {
		return err
	}

	b, err := genManContent(node, header)
	if err != nil {
		return err
	}
	if translate {
		_, err = w.Write(md2man.Render(b))
		return err
	}
	_, err = w.Write(b)
	return err
}

func fillManHeader(header *ManHeader, name string) error {
	if header.Title == "" {
		header.Title = strings.ToUpper(strings.ReplaceAll(name, " ", "\\-"))
	}
	if header.Section == "" {
		header.Section = "1"
	}
	if header.Date == nil {
		now := time.Now()
		if epoch := os.Getenv("SOURCE_DATE_EPOCH"); epoch != "" {
			unixEpoch, err := strconv.ParseInt(epoch, 10, 64)
			if err != nil {
				return fmt.Errorf("invalid SOURCE_DATE_EPOCH: %v", err)
			}
			now = time.Unix(unixEpoch, 0)
		}
		header.Date = &now
	}
	if header.Source == "" {
		header.Source = "Auto generated by Unikraft CLI"
	}
	return nil
}

func genManContent(node *kong.Node, header *ManHeader) ([]byte, error) {
	dashCommandName := strings.ReplaceAll(NodePath(node), " ", "-")
	dateStr := header.Date.Format("Jan 2006")

	buf := new(bytes.Buffer)

	// Preamble
	var description string
	if node.Parent == nil {
		description = node.Help
	} else if node.Detail != "" {
		description = node.Detail
	} else {
		description = node.Help
	}

	fmt.Fprintf(buf, "%% \"%s\" \"%s\" \"%s\" \"%s\" \"%s\"\n",
		header.Title, header.Section, dateStr, header.Source, header.Manual)
	buf.WriteString("# NAME\n")
	fmt.Fprintf(buf, "%s \\- %s\n\n", dashCommandName, node.Help)
	buf.WriteString("# SYNOPSIS\n")
	fmt.Fprintf(buf, "`%s`\n\n", ansi.Strip(kingkong.Summary(node)))
	buf.WriteString("# DESCRIPTION\n")
	buf.WriteString(description + "\n\n")

	manPrintExamples(buf, node)

	// Options
	manPrintOptions(buf, node)

	if err := manPrintFields(buf, node); err != nil {
		return nil, err
	}

	// See also
	hasSeeAlso := false
	for related := range SeeAlso(node) {
		if !hasSeeAlso {
			buf.WriteString("# SEE ALSO\n")
			hasSeeAlso = true
		}
		relatedPath := strings.ReplaceAll(NodePath(related), " ", "-")
		fmt.Fprintf(buf, "**%s(%s)** ", relatedPath, header.Section)
	}
	if hasSeeAlso {
		buf.WriteString("\n")
	}

	// History
	fmt.Fprintf(buf, "# HISTORY\n%s Auto generated by Unikraft CLI\n", header.Date.Format("2-Jan-2006"))

	return buf.Bytes(), nil
}

func manPrintExamples(buf *bytes.Buffer, node *kong.Node) {
	examples := ExamplesForNode(node)
	if len(examples) == 0 {
		return
	}

	buf.WriteString("# EXAMPLES\n\n")
	for _, example := range examples {
		if example.Description != "" {
			buf.WriteString(example.Description + ":\n\n")
		}
		buf.WriteString("> ```\n")
		buf.WriteString(prefixLines(formatExampleCommands(example), "> "))
		buf.WriteString("\n> ```\n\n")
	}
}

func manPrintOptions(buf *bytes.Buffer, node *kong.Node) {
	localFlags := CollectLocalFlags(node)
	if len(localFlags) > 0 {
		buf.WriteString("# OPTIONS\n")
		for _, f := range localFlags {
			manPrintFlag(buf, f)
		}
	}

	inheritedFlags := CollectInheritedFlags(node)
	if len(inheritedFlags) > 0 {
		buf.WriteString("# OPTIONS INHERITED FROM PARENT COMMANDS\n")
		for _, f := range inheritedFlags {
			manPrintFlag(buf, f)
		}
	}
}

func manPrintFields(buf *bytes.Buffer, node *kong.Node) error {
	target, ok := node.Target.Interface().(cmd.ResourceCmdInterface)
	if !ok {
		return nil
	}

	src := target.Underlying()
	fields, err := src.Fields(context.Background())
	if err != nil {
		return fmt.Errorf("could not get fields for %s: %w", NodePath(node), err)
	}
	fields, _ = resource.FilterFieldsByPath(fields, nil, false)
	fields = resource.FilterFields(fields, func(field resource.Field) resource.FilterResult {
		if field.Verbosity < resource.FieldVerbosityHidden {
			return resource.FilterExclude
		}
		return resource.FilterRecurse
	})
	if len(fields) == 0 {
		return nil
	}

	buf.WriteString("# RESOURCE FIELDS\n")
	for i := range fields {
		field := &fields[i]
		manPrintField(buf, field.Name, manFieldGroupDescription(field))
	}
	return nil
}

func manPrintField(buf *bytes.Buffer, path string, description string) {
	if description == "" {
		return
	}
	format := fmt.Sprintf("`%s`", path)
	format += "\n\n\t\t%s\n\n"
	fmt.Fprintf(buf, format, description)
}

func manFieldGroupDescription(field *resource.Field) string {
	lines := []string{}
	if detail := manFieldDetail(field); detail != "" {
		lines = append(lines, detail)
	}
	if subfields := manFieldDescendants(field); len(subfields) > 0 {
		lines = append(lines, "Subfields:")
		lines = append(lines, subfields...)
	}
	return strings.Join(lines, "\n\t\t")
}

func manFieldDescendants(field *resource.Field) []string {
	if len(field.Subfields) == 0 {
		return nil
	}

	descendants := []string{}
	for path, subfield := range resource.IterFields(field.Subfields) {
		fullPath := field.Name + "." + path.String()
		line := manFieldLine(fullPath, subfield)
		if line == "" {
			continue
		}
		descendants = append(descendants, line)
	}
	return descendants
}

func manFieldLine(path string, field *resource.Field) string {
	detail := manFieldDetail(field)
	if detail == "" {
		if field.HasChildren() {
			return ""
		}
		return path
	}
	return fmt.Sprintf("%s: %s", path, detail)
}

func manFieldDetail(field *resource.Field) string {
	var parts []string

	if field.Value != nil {
		typeStr := formatType(reflect.TypeOf(field.Value))
		typeStr = strings.ToLower(typeStr)
		if typeStr != "" {
			parts = append(parts, fmt.Sprintf("Type: %s.", typeStr))
		}
	}

	operations := []string{}
	if field.Create != nil {
		operations = append(operations, "create")
	}
	if field.Edit != nil {
		operations = append(operations, "edit")
	}
	if len(operations) > 0 {
		parts = append(parts, fmt.Sprintf("Operations: %s.", strings.Join(operations, "/")))
	}

	return strings.Join(parts, " ")
}

func manPrintFlag(buf *bytes.Buffer, f *kong.Flag) {
	var format string
	if f.Short != 0 {
		format = fmt.Sprintf("`-%c`, `--%s`", f.Short, f.Name)
	} else {
		format = fmt.Sprintf("`--%s`", f.Name)
	}

	if !f.IsBool() {
		if f.PlaceHolder != "" {
			format += "=" + f.PlaceHolder
		} else {
			format += "=" + strings.ToUpper(f.Name)
		}
	}

	format += "\n\n\t\t%s\n\n"
	fmt.Fprintf(buf, format, f.Help)
}
