name: actionlint

on:
  pull_request:
    branches:
    - staging
    paths:
    - '.github/workflows/**'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Check workflow files
      uses: docker://rhysd/actionlint:latest
      with:
        args: -color -verbose
