name: check/static

on:
  push:
    branches: [staging, stable]
  pull_request:
    branches:
    - staging
    paths:
    - '**'
    - '!.github/**'
    - .github/workflows/check-static.yaml

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  go:
    runs-on: ubuntu-latest
    env:
      TASK_X_REMOTE_TASKFILES: 1
    steps:
    - uses: actions/checkout@v6

    - uses: go-task/setup-task@v2

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Set Go variables
      id: goenv
      run: |
        {
          echo "cache=$(go env GOCACHE)"
          echo "modcache=$(go env GOMODCACHE)"
          echo "mod=$(go env GOMOD)"
        } >>"$GITHUB_OUTPUT"

    - name: Go caches
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.goenv.outputs.cache }}
          ${{ steps.goenv.outputs.modcache }}
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Check that go.mod is tidy
      run: |
        go mod tidy
        git diff --exit-code -- go.sum go.mod

    - name: Golang CI Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        args: --timeout=5m
        skip-cache: true

    - name: Check licenses
      run: |
        task --yes license
