name: docs

on:
  push:
    branches:
    - staging
    paths:
    - '**'
    - '!.github/**'
    - '.github/workflows/docs.yaml'
    - '!README.md'
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - staging
    paths:
    - '**'
    - '!.github/**'
    - '.github/workflows/docs.yaml'
    - '!README.md'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Task
      uses: go-task/setup-task@v2

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Set Go variables
      id: goenv
      run: |
        {
          echo "cache=$(go env GOCACHE)"
          echo "modcache=$(go env GOMODCACHE)"
          echo "mod=$(go env GOMOD)"
        } >>"$GITHUB_OUTPUT"

    - name: Go caches
      uses: actions/cache@v6
      with:
        path: |
          ${{ steps.goenv.outputs.cache }}
          ${{ steps.goenv.outputs.modcache }}
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Build docs
      shell: bash
      run: |
        make docs

    - name: Upload docs artifacts to GitHub
      uses: actions/upload-artifact@v7
      if: github.event_name == 'push'
      with:
        name: unikraft-docs-${{ github.event.pull_request.number || github.sha }}
        path: ./dist/docs/mdx
        if-no-files-found: error
        retention-days: 7
        overwrite: true

    - name: Upload man artifacts to GitHub
      uses: actions/upload-artifact@v7
      if: github.event_name == 'push'
      with:
        name: unikraft-man-${{ github.sha }}
        path: ./dist/docs/man
        if-no-files-found: error
        retention-days: 7
        overwrite: true
