name: release

on:
  push:
    branches:
    - staging
    - stable

permissions:
  contents: write
  packages: write

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Fetch all tags
      shell: bash
      run: git fetch --force --tags

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Set Go variables
      id: goenv
      run: |
        {
          echo "cache=$(go env GOCACHE)"
          echo "modcache=$(go env GOMODCACHE)"
          echo "mod=$(go env GOMOD)"
        } >>"$GITHUB_OUTPUT"

    - name: Go caches
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.goenv.outputs.cache }}
          ${{ steps.goenv.outputs.modcache }}
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Login to GitHub
      shell: bash
      run: |
        git config user.name "Unikraft Bot"
        git config user.email "monkey@unikraft.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

    - name: Gather all versions
      shell: bash
      id: versions
      run: |
        {
          echo "next-stable=$(make --no-print-directory next-stable 2>/dev/null)"
          echo "next-staging=$(make --no-print-directory next-staging 2>/dev/null)"
          echo "last-version=$(make --no-print-directory last-version 2>/dev/null)"
          echo "last-stable=$(make --no-print-directory last-stable 2>/dev/null)"
        } >> "$GITHUB_OUTPUT"

        if [[ "${{ github.ref }}" == "refs/heads/stable" ]]; then
          echo "next-version=$(make --no-print-directory next-stable 2>/dev/null)" >> "$GITHUB_OUTPUT"
        else
          echo "next-version=$(make --no-print-directory next-staging 2>/dev/null)" >> "$GITHUB_OUTPUT"
        fi

    - name: Tag next version
      shell: bash
      run: |
        git tag -a "${{ steps.versions.outputs.next-version }}" -m "${{ steps.versions.outputs.next-version }}"
        git push -u origin "${{ steps.versions.outputs.next-version }}"

    - name: Generate GoReleaser config
      shell: bash
      run: |
        YTT_DEB_RELEASE=""
        YTT_DEB_METADATA="$(git rev-parse --short HEAD)"

        if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          YTT_PRERELEASE=true
          YTT_DEB_EPOCH=1
          YTT_DEB_PRERELEASE=$(echo "${{ steps.versions.outputs.next-version }}" | awk -F'staging\\.' '{print $2}')
          NEXT_VERSION="${{ steps.versions.outputs.next-version }}"
          NEXT_VERSION="${NEXT_VERSION%%-*}"
          YTT_DEB_PRERELEASE_VERSION="${NEXT_VERSION#v}~${YTT_DEB_PRERELEASE}+${YTT_DEB_METADATA}"
        else
          YTT_PRERELEASE=false
          YTT_DEB_EPOCH=5
          YTT_DEB_PRERELEASE=""
          YTT_DEB_PRERELEASE_VERSION=""
        fi

        export YTT_PRERELEASE
        export YTT_DEB_EPOCH
        export YTT_DEB_PRERELEASE
        export YTT_DEB_METADATA
        export YTT_DEB_RELEASE
        export YTT_DEB_PRERELEASE_VERSION
        make goreleaser-yaml

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_PREVIOUS_TAG: ${{ github.ref == 'refs/heads/stable' && steps.versions.outputs.last-stable || steps.versions.outputs.last-version }}
        GORELEASER_CURRENT_TAG: ${{ steps.versions.outputs.next-version }}
        UNIKRAFT_POSTHOG_API_KEY: ${{ secrets.UNIKRAFT_POSTHOG_API_KEY }}
        UNIKRAFT_POSTHOG_HOST: ${{ secrets.UNIKRAFT_POSTHOG_HOST }}
      with:
        version: latest
        args: release --clean

    - name: Publish to APT repository
      shell: bash
      run: |
        COMPONENT=stable
        if [[ "${GITHUB_REF#refs/tags/v}" == *"staging"* ]]; then
          COMPONENT=staging
        fi

        DISTROS=()
        # Debian
        DISTROS+=("bullseye") # 11
        DISTROS+=("bookworm") # 12
        DISTROS+=("trixie")   # 13
        # Ubuntu
        DISTROS+=("jammy")     # 22.04
        DISTROS+=("noble")     # 24.04
        DISTROS+=("plucky")    # 25.05
        DISTROS+=("questing")  # 25.10
        DISTROS+=("resolute")  # 26.04 (preview)

        for DISTRO in "${DISTROS[@]}"; do
          for DEB in dist/*.deb; do
            curl "https://pkg.unikraft.com/debian/cli-apt/upload/${DISTRO}/${COMPONENT}" \
              --user "api:${{ secrets.PKG_TOKEN }}" \
              --upload-file "${DEB}"
          done
        done

    - name: Publish to RPM repository
      shell: bash
      run: |
        for RPM in dist/*.rpm; do
          curl "https://pkg.unikraft.com/rpm/cli-rpm" \
            --user "api:${{ secrets.PKG_TOKEN }}" \
            --upload-file "${RPM}"
        done

    - name: Publish to APK repository
      shell: bash
      run: |
        for APK in dist/*.apk; do
          curl "https://pkg.unikraft.com/apk/cli-apk" \
            --user "api:${{ secrets.PKG_TOKEN }}" \
            --upload-file "${APK}"
        done

