name: test
permissions:
  contents: read

on:
  push:
    branches: [staging, stable]
  pull_request:
    branches: [staging]
    paths:
    - '**'
    - '!.github/**'
    - '.github/workflows/test.yaml'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}

jobs:
  go:
    runs-on: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork && 'ubuntu-latest' || 'arc-unikraft-cli-ubuntu24.04-standard' }}
    env:
      TASK_X_REMOTE_TASKFILES: 1
    steps:
      - uses: actions/checkout@v6
      - uses: go-task/setup-task@v1
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Set Go variables
        id: goenv
        run: |
          {
            echo "cache=$(go env GOCACHE)"
            echo "modcache=$(go env GOMODCACHE)"
            echo "mod=$(go env GOMOD)"
          } >>"$GITHUB_OUTPUT"

      - name: Go caches
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.goenv.outputs.cache }}
            ${{ steps.goenv.outputs.modcache }}
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - name: Run unit tests
        shell: bash
        run: |
          task --yes unit-race

      - name: Run integration tests (without auth)
        if: ${{ !(github.event_name == 'push' || !github.event.pull_request.head.repo.fork) }}
        shell: bash
        run: |
          task --yes integration

      - name: Run integration tests (with auth)
        if: ${{ github.event_name == 'push' || !github.event.pull_request.head.repo.fork }}
        shell: bash
        run: |
          mkdir -p ~/.config/unikraft
          echo "${UNIKRAFT_CONFIG}" > ~/.config/unikraft/config.yaml
          task --yes integration
        env:
          UNIKRAFT_CONFIG: ${{ secrets.UNIKRAFT_CONFIG }}
